apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      nodeSelector:
        node-role: app 
      containers:
      - name: my-app-container
        image: nginx  # 替換為你自己的容器映像
        resources:
          requests:
            cpu: "100m"
          limits:
            cpu: "500m"

